Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 1024
  end

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "manager1" do |manager1|
    manager1.vm.hostname = "manager1"
    manager1.vm.network "forwarded_port", guest: 1101, host: 1101
    manager1.vm.network "forwarded_port", guest: 1102, host: 1102
    manager1.vm.network "forwarded_port", guest: 1103, host: 1103
    manager1.vm.network "private_network", ip: "192.168.56.10", netmask: "24"
    manager1.vm.provision "shell", path: "install_docker.sh"
    manager1.vm.provision "shell", inline: "docker swarm init --advertise-addr 192.168.56.10"
    manager1.vm.provision "shell", inline: "docker swarm join-token -q worker > /vagrant/token"
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.56.11", netmask: "24"
    worker1.vm.provision "shell", path: "install_docker.sh"
    worker1.vm.provision "shell", inline: "docker swarm join --token `cat /vagrant/token` 192.168.56.10:2377"
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.56.12", netmask: "24"
    worker2.vm.provision "shell", path: "install_docker.sh"
    worker2.vm.provision "shell", inline: "docker swarm join --token `cat /vagrant/token` 192.168.56.10:2377"
  end

  config.vm.define "manager1" do |manager1|
    manager1.vm.provision "shell", inline: "docker stack deploy --detach=false -c /vagrant/docker-compose.yml services"
  end

end
