Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "ubuntu/jammy64"
    vm1.vm.hostname = "vm1"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080
    vm1.vm.network "private_network", ip: "172.20.0.10"
    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y nginx
      sudo systemctl start nginx
      sudo systemctl enable nginx
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "ubuntu/jammy64"
    vm2.vm.hostname = "vm2"
    vm2.disksize.size = '40GB'
    vm2.vm.network "public_network"
    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
      sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      sudo apt-get update
      sudo apt-get install -y docker-ce
      sudo systemctl start docker
      sudo systemctl enable docker
    SHELL
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.box = "ubuntu/jammy64"
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "172.20.0.11"
    vm3.vm.provision "shell", inline: <<-SHELL
      sudo useradd -m -s /bin/zsh -G sudo adam
      echo 'adam ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/adam
    SHELL
  end

  config.ssh.insert_key = false

end
